services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - 8080:8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
  
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - pg-data:/var/lib/postgresql/data/
      - ./backend/db/migration/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg-data: