apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: default
data:
  grafana.ini: |
    [security]
    admin_user = admin
    admin_password = admin

    [paths]
    provisioning = /etc/grafana/provisioning
