apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swipemytalent
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/swipemytalent/SwipeMyTalent
    path: infra/k8s/prod
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
