name: CI

on:
  pull_request:

jobs:
  build:
    name: Build services
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    name: Test services
    uses: ./.github/workflows/test.yaml
